apiVersion: v1
kind: Service
metadata:
  name: train-schedule-service
spec:
  selector:
    app: train-schedule
  ports:
    - protocol: TCP
      port: 80  # External port (for accessing the service)
      targetPort: 8080  # Port inside the container
  type: LoadBalancer
